

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0x0726fa885352a7b2fd908b27c487b7427057a719761ce1b0ab19a1f2406e3266


actor EOA as "EOA"
participant GoodGhosting_01 as "GoodGhosting_01"
participant Context_01 as "Context_01"
participant Ownable_01 as "Ownable_01"
participant Pausable_01 as "Pausable_01"

"EOA" -> "GoodGhosting_01" ++: pause()
"GoodGhosting_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |\n\
)
"GoodGhosting_01" -> "Ownable_01" ++: owner()
"Ownable_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |\n\
)
"GoodGhosting_01" -> "Pausable_01" ++: paused()
"Pausable_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| bool |  | false |\n\
)
"GoodGhosting_01" -> "Pausable_01" ++: _pause()
"Pausable_01" -> "Pausable_01" ++: paused()
"Pausable_01" -> "Pausable_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| bool |  | false |\n\
)
"Pausable_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "Pausable_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |\n\
)
"Pausable_01" -> "GoodGhosting_01" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| GoodGhosting_01 | GoodGhosting | 0x76dB7B81b681132a419F8E0b3e1D819F436eA04a |
<#FEFECE>| Context_01 | Context | 0x76dB7B81b681132a419F8E0b3e1D819F436eA04a |
<#FEFECE>| Ownable_01 | Ownable | 0x76dB7B81b681132a419F8E0b3e1D819F436eA04a |
<#FEFECE>| Pausable_01 | Pausable | 0x76dB7B81b681132a419F8E0b3e1D819F436eA04a |
endlegend

@enduml