

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0x26782aca4bf4c27c6f7a488c8be3016272aa3f78ac827d95204394919829f70b


actor EOA as "EOA"
participant GoodGhosting_01 as "GoodGhosting_01"
participant Context_01 as "Context_01"

"EOA" -> "GoodGhosting_01" ++: constructor(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| contract | _inboundCurrency | 0x8e4C131B37383E431B9cd0635D3cF9f3F628EDae (MockERC20Mintable) |\n\
| contract | _lendingPoolAddressProvider | 0x4a5cd58b24e3BF04360B06bFEaF45A39aA8035b6 (LendingPoolAddressesProviderMock) |\n\
| uint | _segmentCount | 6 |\n\
| uint | _segmentLength | 180 |\n\
| uint | _segmentPayment | 10000000000000000000 |\n\
| uint | _earlyWithdrawalFee | 9 |\n\
| uint | _customFee | 30 |\n\
| address | _dataProvider | 0x4a5cd58b24e3BF04360B06bFEaF45A39aA8035b6 |\n\
| bytes | merkleRoot_ | 0xd53ed7372825e2b21778b03e7f08246a9e358bf89416c856ebb4f196fca5e662 |\n\
) { 0.0 GWEI }
"GoodGhosting_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |\n\
)
"GoodGhosting_01" x-[#red]-> "EOA" --: <&warning> <color #red>**REVERT!**</color>
deactivate "GoodGhosting_01"

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| GoodGhosting_01 | GoodGhosting | 0xCB152A2Aa90055a0D255cA7dbaeb85eDFdc86096 |
<#FEFECE>| Context_01 | Context | 0xCB152A2Aa90055a0D255cA7dbaeb85eDFdc86096 |
endlegend

@enduml