

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0x44b557428efe50ce2130de54b9fafae7155abddad715b4f0e97b777b55948d5a


actor EOA as "EOA"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"
participant Context_01 as "Context_01"
participant ERC20_01 as "ERC20_01"

"EOA" -> "MockERC20Mintable_01" ++: approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | spender | 0x5e8DF2840b3B1e515DDa7a61Bf9b7A45a94570EC |\n\
| uint | amount | 10000000000000000000 |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "MockERC20Mintable_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0xf17f52151EbEF6C7334FAD080c5704D77216b732 |\n\
)
"MockERC20Mintable_01" -> "ERC20_01" ++: _approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | owner | 0x0000000000000000000000008AC7230489e80000 |\n\
| address | spender | 0x0000000000000000000000000000000000000000 |\n\
| uint | amount | 954 |\n\
) { 0.0 GWEI }
"ERC20_01" -> "MockERC20Mintable_01" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0xf17f52151EbEF6C7334FAD080c5704D77216b732 |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0x4fbe0607e4afc05ce2b19B1da889E49c38D09b63 |
<#FEFECE>| Context_01 | Context | 0x4fbe0607e4afc05ce2b19B1da889E49c38D09b63 |
<#FEFECE>| ERC20_01 | ERC20 | 0x4fbe0607e4afc05ce2b19B1da889E49c38D09b63 |
endlegend

@enduml