

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0x5efefdb01f9b02f683e3cd2228059086382a30dc4cf5e47cb7ec63937fea346c


actor EOA as "EOA"
participant GoodGhosting_01 as "GoodGhosting_01"
participant Pausable_01 as "Pausable_01"
participant SafeMath_01 as "SafeMath_01"

"EOA" -> "GoodGhosting_01" ++: makeDeposit()
"GoodGhosting_01" -> "Pausable_01" ++: paused()
"Pausable_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| bool |  | false |\n\
)
"GoodGhosting_01" -> "GoodGhosting_01" ++: getCurrentSegment()
"GoodGhosting_01" -> "SafeMath_01" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 1621657870 |\n\
| uint | b | 1621657510 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 360 |\n\
)
"GoodGhosting_01" -> "SafeMath_01" ++: div(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 360 |\n\
| uint | b | 180 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 2 |\n\
)
"GoodGhosting_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 2 |\n\
)
"GoodGhosting_01" -> "SafeMath_01" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 2 |\n\
| uint | b | 1 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 1 |\n\
)
"GoodGhosting_01" x-[#red]-> "EOA" --: <&warning> <color #red>**REVERT!**</color> (\n\
<#FEFECE,#FEFECE>| string |  | "Player didn't pay the previous segment - game over!" |\n\
)
deactivate "GoodGhosting_01"

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0xf17f52151EbEF6C7334FAD080c5704D77216b732 |
<#FEFECE>| GoodGhosting_01 | GoodGhosting | 0x13C72f3c8bC7AfC2609a9da61a0d185c50085Cf8 |
<#FEFECE>| Pausable_01 | Pausable | 0x13C72f3c8bC7AfC2609a9da61a0d185c50085Cf8 |
<#FEFECE>| SafeMath_01 | SafeMath | 0x13C72f3c8bC7AfC2609a9da61a0d185c50085Cf8 |
endlegend

@enduml