

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0x658092723095e3eaf9de62ee2fcc49c848c3dc4909d1caa217774909b81a7020


actor EOA as "EOA"
participant GoodGhosting_01 as "GoodGhosting_01"
participant SafeMath_01 as "SafeMath_01"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"
participant Context_01 as "Context_01"
participant undefined_01 as "undefined_01"
participant ERC20_01 as "ERC20_01"
participant SafeMath_02 as "SafeMath_02"

"EOA" -> "GoodGhosting_01" ++: withdraw()
"GoodGhosting_01" -> "SafeMath_01" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 6 |\n\
| uint | b | 1 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 5 |\n\
)
"GoodGhosting_01" -> "SafeMath_01" ++: div(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 0 |\n\
| uint | b | 1 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"GoodGhosting_01" -> "SafeMath_01" ++: add(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 60000000000000000000 |\n\
| uint | b | 0 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "MockERC20Mintable_01" ++: transfer(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | recipient | 0xf17f52151EbEF6C7334FAD080c5704D77216b732 |\n\
| uint | amount | 60000000000000000000 |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "MockERC20Mintable_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0xE6B0a577D28879305B2564D13c7c40bb24656A70 |\n\
)
"MockERC20Mintable_01" -> "undefined_01" ++: unknown-internal-name()
"undefined_01" -> "ERC20_01" ++: _beforeTokenTransfer(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | from | 0xf17f52151EbEF6C7334FAD080c5704D77216b732 |\n\
| address | to | 0x00000000000000000000000340AAd21b3b700000 |\n\
| uint | amount | 1901 |\n\
) { 0.0 GWEI }
"ERC20_01" -> "SafeMath_02" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 60000000000000000000 |\n\
| uint | b | 60000000000000000000 |\n\
| string | errorMessage | 'ERC20: transfer amount exceeds balance' |\n\
) { 0.0 GWEI }
"SafeMath_02" -> "ERC20_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"ERC20_01" -> "SafeMath_02" ++: add(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 940000000000000000000 |\n\
| uint | b | 60000000000000000000 |\n\
) { 0.0 GWEI }
"SafeMath_02" -> "ERC20_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 1000000000000000000000 |\n\
)
"ERC20_01" -> "undefined_01" --: 
"SafeMath_01" -> "GoodGhosting_01" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0xf17f52151EbEF6C7334FAD080c5704D77216b732 |
<#FEFECE>| GoodGhosting_01 | GoodGhosting | 0xE6B0a577D28879305B2564D13c7c40bb24656A70 |
<#FEFECE>| SafeMath_01 | SafeMath | 0xE6B0a577D28879305B2564D13c7c40bb24656A70 |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0xe5fcB7960Adc9F0bCd88dAa3C699E01836Fcd24f |
<#FEFECE>| Context_01 | Context | 0xe5fcB7960Adc9F0bCd88dAa3C699E01836Fcd24f |
<#FEFECE>| undefined_01 | undefined | 0xe5fcB7960Adc9F0bCd88dAa3C699E01836Fcd24f |
<#FEFECE>| ERC20_01 | ERC20 | 0xe5fcB7960Adc9F0bCd88dAa3C699E01836Fcd24f |
<#FEFECE>| SafeMath_02 | SafeMath | 0xe5fcB7960Adc9F0bCd88dAa3C699E01836Fcd24f |
endlegend

@enduml