

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0x6f1354d655371e70d4b9ef4bfbec24d1854b3da364221e2a82809003bba59761


actor EOA as "EOA"
participant GoodGhosting_01 as "GoodGhosting_01"
participant Pausable_01 as "Pausable_01"

"EOA" -> "GoodGhosting_01" ++: earlyWithdraw()
"GoodGhosting_01" -> "Pausable_01" ++: paused()
"Pausable_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| bool |  | true |\n\
)
"GoodGhosting_01" x-[#red]-> "EOA" --: <&warning> <color #red>**REVERT!**</color> (\n\
<#FEFECE,#FEFECE>| string |  | 'Pausable: paused' |\n\
)
deactivate "GoodGhosting_01"

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0xf17f52151EbEF6C7334FAD080c5704D77216b732 |
<#FEFECE>| GoodGhosting_01 | GoodGhosting | 0xfc0A7938B9fC084039f3E1D059BA8B94da0d43A5 |
<#FEFECE>| Pausable_01 | Pausable | 0xfc0A7938B9fC084039f3E1D059BA8B94da0d43A5 |
endlegend

@enduml