

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0x74d49e02e0a982ac69be124c22628a11f09f6cf145a52785163e03e3e928c6ac


actor EOA as "EOA"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"

"EOA" -> "MockERC20Mintable_01" ++: constructor(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| string | name | 'MINT' |\n\
| string | symbol | 'MINT' |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "EOA" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0xB9B7e0cb2EDF5Ea031C8B297A5A1Fa20379b6A0a |
endlegend

@enduml