

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0x94bb884fabab09b66fe9483390fa6fef9456781ac34929fca42a30c797787fd0


actor EOA as "EOA"
participant GoodGhosting_01 as "GoodGhosting_01"
participant SafeMath_01 as "SafeMath_01"
participant LendingPoolAddressesProviderMock_01 as "LendingPoolAddressesProviderMock_01"
participant undefined_01 as "undefined_01"
participant ERC20_01 as "ERC20_01"
participant SafeMath_02 as "SafeMath_02"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"
participant Context_01 as "Context_01"
participant undefined_02 as "undefined_02"
participant ERC20_02 as "ERC20_02"
participant SafeMath_03 as "SafeMath_03"

"EOA" -> "GoodGhosting_01" ++: redeemFromExternalPool()
"GoodGhosting_01" -> "GoodGhosting_01" ++: isGameCompleted()
"GoodGhosting_01" -> "GoodGhosting_01" ++: getCurrentSegment()
"GoodGhosting_01" -> "SafeMath_01" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 1621681561 |\n\
| uint | b | 1621680300 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 1261 |\n\
)
"GoodGhosting_01" -> "SafeMath_01" ++: div(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 1261 |\n\
| uint | b | 180 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 7 |\n\
)
"GoodGhosting_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 7 |\n\
)
"GoodGhosting_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| bool |  | true |\n\
)
"GoodGhosting_01" -> "LendingPoolAddressesProviderMock_01" ++: balanceOf(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | account | 0x5F80759241b2A868DC5A5216901D05c3763DC5cC |\n\
) { 0.0 GWEI }
"LendingPoolAddressesProviderMock_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 60000000000000000000 |\n\
)
"GoodGhosting_01" -> "LendingPoolAddressesProviderMock_01" ++: withdraw(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | asset | 0x4BE080246b09f31f795a1ac22B0624F36fD2f11e |\n\
| uint | amount | 115792089237316195423570985008687907853269984665640564039457584007913129639935 |\n\
| address | to | 0x5F80759241b2A868DC5A5216901D05c3763DC5cC |\n\
) { 0.0 GWEI }
"LendingPoolAddressesProviderMock_01" -> "LendingPoolAddressesProviderMock_01" ++: balanceOf(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | account | 0x5F80759241b2A868DC5A5216901D05c3763DC5cC |\n\
) { 0.0 GWEI }
"LendingPoolAddressesProviderMock_01" -> "LendingPoolAddressesProviderMock_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 60000000000000000000 |\n\
)
"LendingPoolAddressesProviderMock_01" -> "undefined_01" ++: unknown-internal-name()
"undefined_01" -> "ERC20_01" ++: _beforeTokenTransfer(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | from | 0x5F80759241b2A868DC5A5216901D05c3763DC5cC |\n\
| address | to | 0x00000000000000000000000340AAd21b3b700000 |\n\
| uint | amount | 3984 |\n\
) { 0.0 GWEI }
"ERC20_01" -> "SafeMath_02" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 60000000000000000000 |\n\
| uint | b | 60000000000000000000 |\n\
| string | errorMessage | 'ERC20: burn amount exceeds balance' |\n\
) { 0.0 GWEI }
"SafeMath_02" -> "ERC20_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"ERC20_01" -> "SafeMath_02" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 60000000000000000000 |\n\
| uint | b | 60000000000000000000 |\n\
) { 0.0 GWEI }
"SafeMath_02" -> "ERC20_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"ERC20_01" -> "MockERC20Mintable_01" ++: transfer(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | recipient | 0x5F80759241b2A868DC5A5216901D05c3763DC5cC |\n\
| uint | amount | 60000000000000000000 |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "MockERC20Mintable_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0xf59d5F79AB2306eF96eD86f190FBAF723D1cF417 |\n\
)
"MockERC20Mintable_01" -> "undefined_02" ++: unknown-internal-name()
"undefined_02" -> "ERC20_02" ++: _beforeTokenTransfer(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | from | 0x5F80759241b2A868DC5A5216901D05c3763DC5cC |\n\
| address | to | 0x00000000000000000000000340AAd21b3b700000 |\n\
| uint | amount | 1901 |\n\
) { 0.0 GWEI }
"ERC20_02" -> "SafeMath_03" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 60000000000000000000 |\n\
| uint | b | 60000000000000000000 |\n\
| string | errorMessage | 'ERC20: transfer amount exceeds balance' |\n\
) { 0.0 GWEI }
"SafeMath_03" -> "ERC20_02" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"ERC20_02" -> "SafeMath_03" ++: add(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 0 |\n\
| uint | b | 60000000000000000000 |\n\
) { 0.0 GWEI }
"SafeMath_03" -> "ERC20_02" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 60000000000000000000 |\n\
)
"ERC20_02" -> "undefined_02" --: 
"ERC20_01" -> "undefined_01" --: 
"GoodGhosting_01" -> "MockERC20Mintable_01" ++: balanceOf(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | account | 0x5F80759241b2A868DC5A5216901D05c3763DC5cC |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 60000000000000000000 |\n\
)
"GoodGhosting_01" -> "SafeMath_01" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 60000000000000000000 |\n\
| uint | b | 60000000000000000000 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"GoodGhosting_01" -> "SafeMath_01" ++: mul(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 0 |\n\
| uint | b | 5 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"GoodGhosting_01" -> "SafeMath_01" ++: div(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 0 |\n\
| uint | b | 100 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"GoodGhosting_01" -> "SafeMath_01" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 0 |\n\
| uint | b | 0 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"GoodGhosting_01" -> "EOA" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| GoodGhosting_01 | GoodGhosting | 0x5F80759241b2A868DC5A5216901D05c3763DC5cC |
<#FEFECE>| SafeMath_01 | SafeMath | 0x5F80759241b2A868DC5A5216901D05c3763DC5cC |
<#FEFECE>| LendingPoolAddressesProviderMock_01 | LendingPoolAddressesProviderMock | 0xf59d5F79AB2306eF96eD86f190FBAF723D1cF417 |
<#FEFECE>| undefined_01 | undefined | 0xf59d5F79AB2306eF96eD86f190FBAF723D1cF417 |
<#FEFECE>| ERC20_01 | ERC20 | 0xf59d5F79AB2306eF96eD86f190FBAF723D1cF417 |
<#FEFECE>| SafeMath_02 | SafeMath | 0xf59d5F79AB2306eF96eD86f190FBAF723D1cF417 |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0x4BE080246b09f31f795a1ac22B0624F36fD2f11e |
<#FEFECE>| Context_01 | Context | 0x4BE080246b09f31f795a1ac22B0624F36fD2f11e |
<#FEFECE>| undefined_02 | undefined | 0x4BE080246b09f31f795a1ac22B0624F36fD2f11e |
<#FEFECE>| ERC20_02 | ERC20 | 0x4BE080246b09f31f795a1ac22B0624F36fD2f11e |
<#FEFECE>| SafeMath_03 | SafeMath | 0x4BE080246b09f31f795a1ac22B0624F36fD2f11e |
endlegend

@enduml