

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xabe1e217bb2852f174f60ef8e3fbf1eeeab7fc8ccda66a286095296ad9d81164


actor EOA as "EOA"
participant LendingPoolAddressesProviderMock_01 as "LendingPoolAddressesProviderMock_01"

"EOA" -> "LendingPoolAddressesProviderMock_01" ++: constructor(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| string | name | 'TOKEN_NAME' |\n\
| string | symbol | 'TOKEN_SYMBOL' |\n\
) { 0.0 GWEI }
"LendingPoolAddressesProviderMock_01" -> "EOA" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| LendingPoolAddressesProviderMock_01 | LendingPoolAddressesProviderMock | 0x4a5cd58b24e3BF04360B06bFEaF45A39aA8035b6 |
endlegend

@enduml