

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xbae85d1022e11ab8ba0cc993e4f663b71982a4d8cb086a9ed87017059e18de8c


actor EOA as "EOA"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"
participant Context_01 as "Context_01"
participant ERC20_01 as "ERC20_01"

"EOA" -> "MockERC20Mintable_01" ++: approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | spender | 0x55F96411Ff9e424e172aB2Aa79fa5f19B09632Ce |\n\
| uint | amount | 10000000000000000000 |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "MockERC20Mintable_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0xC5fdf4076b8F3A5357c5E395ab970B5B54098Fef |\n\
)
"MockERC20Mintable_01" -> "ERC20_01" ++: _approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | owner | 0x0000000000000000000000008AC7230489e80000 |\n\
| address | spender | 0x0000000000000000000000000000000000000000 |\n\
| uint | amount | 954 |\n\
) { 0.0 GWEI }
"ERC20_01" -> "MockERC20Mintable_01" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0xC5fdf4076b8F3A5357c5E395ab970B5B54098Fef |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0xaA780861DA3d81D3eCef0d2CcfB8ba58466a5dE9 |
<#FEFECE>| Context_01 | Context | 0xaA780861DA3d81D3eCef0d2CcfB8ba58466a5dE9 |
<#FEFECE>| ERC20_01 | ERC20 | 0xaA780861DA3d81D3eCef0d2CcfB8ba58466a5dE9 |
endlegend

@enduml