

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xbac1a0d457cb8bb110c1b2e4c91ec0277189e3c46cb1b43a23a2ec4b6cf46027


actor EOA as "EOA"
participant LendingPoolAddressesProviderMock_01 as "LendingPoolAddressesProviderMock_01"

"EOA" -> "LendingPoolAddressesProviderMock_01" ++: setUnderlyingAssetAddress(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | _addr | 0x0bFE658740556A3277fa529A6BbC265d5f65B516 |\n\
) { 0.0 GWEI }
"LendingPoolAddressesProviderMock_01" -> "EOA" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| LendingPoolAddressesProviderMock_01 | LendingPoolAddressesProviderMock | 0x0893C3937aCc139643Fe3641c27A59a312897a04 |
endlegend

@enduml