

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xbf2f52f061fd59c2797111e8a286af8ff55153cdfce1c116fea19b914f191d7f


actor EOA as "EOA"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"

"EOA" -> "MockERC20Mintable_01" ++: constructor(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| string | name | 'MINT' |\n\
| string | symbol | 'MINT' |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "EOA" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0x8b9310d456A72bea86E3C2eAd7e7F47625d2ef34 |
endlegend

@enduml