

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xc15b2562c076fed3390f8707285ba97b6ea14dea906474971303fa5b688c0bbf


actor EOA as "EOA"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"
participant Context_01 as "Context_01"
participant ERC20_01 as "ERC20_01"

"EOA" -> "MockERC20Mintable_01" ++: approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | spender | 0x13C72f3c8bC7AfC2609a9da61a0d185c50085Cf8 |\n\
| uint | amount | 10000000000000000000 |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "MockERC20Mintable_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0xf17f52151EbEF6C7334FAD080c5704D77216b732 |\n\
)
"MockERC20Mintable_01" -> "ERC20_01" ++: _approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | owner | 0x0000000000000000000000008AC7230489e80000 |\n\
| address | spender | 0x0000000000000000000000000000000000000000 |\n\
| uint | amount | 954 |\n\
) { 0.0 GWEI }
"ERC20_01" -> "MockERC20Mintable_01" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0xf17f52151EbEF6C7334FAD080c5704D77216b732 |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0x58056F51402E855CD7670ae4e842Fc95c227CD83 |
<#FEFECE>| Context_01 | Context | 0x58056F51402E855CD7670ae4e842Fc95c227CD83 |
<#FEFECE>| ERC20_01 | ERC20 | 0x58056F51402E855CD7670ae4e842Fc95c227CD83 |
endlegend

@enduml