

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xc19b589e24677861c08030973da0dee9f15931052b01b311ab8ef29d20fdeba6


actor EOA as "EOA"
participant LendingPoolAddressesProviderMock_01 as "LendingPoolAddressesProviderMock_01"

"EOA" -> "LendingPoolAddressesProviderMock_01" ++: setUnderlyingAssetAddress(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | _addr | 0xe547Baa852602c90e641d0e9d6B0d279AFC09f92 |\n\
) { 0.0 GWEI }
"LendingPoolAddressesProviderMock_01" -> "EOA" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| LendingPoolAddressesProviderMock_01 | LendingPoolAddressesProviderMock | 0xd67427275C12474bdaD3b0e68395b1337A319feC |
endlegend

@enduml