

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xc283621486bb2aef08b01a67f81f00ec0cb6492a6d15a4cca35fc7f50ca0c000


actor EOA as "EOA"
participant LendingPoolAddressesProviderMock_01 as "LendingPoolAddressesProviderMock_01"

"EOA" -> "LendingPoolAddressesProviderMock_01" ++: setUnderlyingAssetAddress(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | _addr | 0x90FBC44Fc6f93b773D0111B830bb27CD42292C9F |\n\
) { 0.0 GWEI }
"LendingPoolAddressesProviderMock_01" -> "EOA" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| LendingPoolAddressesProviderMock_01 | LendingPoolAddressesProviderMock | 0x5cA9f95992eb68163EfdF8bf751e813F2C53c450 |
endlegend

@enduml