

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xc389f658965c079ea631eae1c069db376d83cf6f13595047075fd4d94f279a7b


actor EOA as "EOA"
participant GoodGhosting_01 as "GoodGhosting_01"
participant Context_01 as "Context_01"
participant LendingPoolAddressesProviderMock_01 as "LendingPoolAddressesProviderMock_01"
participant undefined_01 as "undefined_01"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"
participant ERC20_01 as "ERC20_01"
participant Context_02 as "Context_02"

"EOA" -> "GoodGhosting_01" ++: constructor(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| contract | _inboundCurrency | 0x447Db080264BeD6Ed21D3a082aE4cdd7eBfe4E32 (MockERC20Mintable) |\n\
| contract | _lendingPoolAddressProvider | 0xe161f0340948199Fa3Ad5819D72d52ec4643f488 (LendingPoolAddressesProviderMock) |\n\
| uint | _segmentCount | 6 |\n\
| uint | _segmentLength | 180 |\n\
| uint | _segmentPayment | 10000000000000000000 |\n\
| uint | _earlyWithdrawalFee | 9 |\n\
| uint | _customFee | 5 |\n\
| address | _dataProvider | 0xe161f0340948199Fa3Ad5819D72d52ec4643f488 |\n\
| bytes | merkleRoot_ | 0xd53ed7372825e2b21778b03e7f08246a9e358bf89416c856ebb4f196fca5e662 |\n\
) { 0.0 GWEI }
"GoodGhosting_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |\n\
)
"GoodGhosting_01" -> "LendingPoolAddressesProviderMock_01" ++: getLendingPool()
"LendingPoolAddressesProviderMock_01" -> "LendingPoolAddressesProviderMock_01" ++: getLendingPool()
"LendingPoolAddressesProviderMock_01" -> "LendingPoolAddressesProviderMock_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0xe161f0340948199Fa3Ad5819D72d52ec4643f488 |\n\
)
"LendingPoolAddressesProviderMock_01" -> "GoodGhosting_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0xe161f0340948199Fa3Ad5819D72d52ec4643f488 |\n\
)
"GoodGhosting_01" -> "LendingPoolAddressesProviderMock_01" ++: getReserveTokensAddresses(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | asset | 0x447Db080264BeD6Ed21D3a082aE4cdd7eBfe4E32 |\n\
) { 0.0 GWEI }
"LendingPoolAddressesProviderMock_01" -> "undefined_01" ++: unknown-internal-name()
"undefined_01" -> "LendingPoolAddressesProviderMock_01" --: 
"GoodGhosting_01" -> "MockERC20Mintable_01" ++: approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | spender | 0xe161f0340948199Fa3Ad5819D72d52ec4643f488 |\n\
| uint | amount | 115792089237316195423570985008687907853269984665640564039457584007913129639935 |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "ERC20_01" ++: approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | spender | 0xe161f0340948199Fa3Ad5819D72d52ec4643f488 |\n\
| uint | amount | 115792089237316195423570985008687907853269984665640564039457584007913129639935 |\n\
) { 0.0 GWEI }
"ERC20_01" -> "Context_02" ++: _msgSender()
"Context_02" -> "ERC20_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0x5B3C2C61643515Ec7354cC8d6E8FBfF040e5FdB1 |\n\
)
"ERC20_01" -> "ERC20_01" ++: _approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | owner | 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF |\n\
| address | spender | 0x0000000000000000000000000000000000000000 |\n\
| uint | amount | 954 |\n\
) { 0.0 GWEI }
"ERC20_01" -> "ERC20_01" --: 
"GoodGhosting_01" -> "EOA" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| GoodGhosting_01 | GoodGhosting | 0x5B3C2C61643515Ec7354cC8d6E8FBfF040e5FdB1 |
<#FEFECE>| Context_01 | Context | 0x5B3C2C61643515Ec7354cC8d6E8FBfF040e5FdB1 |
<#FEFECE>| LendingPoolAddressesProviderMock_01 | LendingPoolAddressesProviderMock | 0xe161f0340948199Fa3Ad5819D72d52ec4643f488 |
<#FEFECE>| undefined_01 | undefined | 0xe161f0340948199Fa3Ad5819D72d52ec4643f488 |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0x447Db080264BeD6Ed21D3a082aE4cdd7eBfe4E32 |
<#FEFECE>| ERC20_01 | ERC20 | 0x447Db080264BeD6Ed21D3a082aE4cdd7eBfe4E32 |
<#FEFECE>| Context_02 | Context | 0x447Db080264BeD6Ed21D3a082aE4cdd7eBfe4E32 |
endlegend

@enduml