

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xd9c526ac0184a9e8623c496c6db5df08a251f453b3d80d024e6dea066ab1bfc7


actor EOA as "EOA"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"
participant Context_01 as "Context_01"
participant ERC20_01 as "ERC20_01"

"EOA" -> "MockERC20Mintable_01" ++: approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | spender | 0xC5F8516c6BdF1d503D767b03f8e42139C532C7da |\n\
| uint | amount | 1000000000000000000000 |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "MockERC20Mintable_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |\n\
)
"MockERC20Mintable_01" -> "ERC20_01" ++: _approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | owner | 0x00000000000000000000003635c9aDC5dEA00000 |\n\
| address | spender | 0x0000000000000000000000000000000000000000 |\n\
| uint | amount | 954 |\n\
) { 0.0 GWEI }
"ERC20_01" -> "MockERC20Mintable_01" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0x391737864A8DcdC7B790877DD1B06cFb99067272 |
<#FEFECE>| Context_01 | Context | 0x391737864A8DcdC7B790877DD1B06cFb99067272 |
<#FEFECE>| ERC20_01 | ERC20 | 0x391737864A8DcdC7B790877DD1B06cFb99067272 |
endlegend

@enduml