

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xda14d6d08ba69b8d28160faf74d0b5ad2f087baa1bb6733afd06a29e34da40b6


actor EOA as "EOA"
participant LendingPoolAddressesProviderMock_01 as "LendingPoolAddressesProviderMock_01"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"
participant undefined_01 as "undefined_01"
participant ERC20_01 as "ERC20_01"
participant SafeMath_01 as "SafeMath_01"
participant Context_01 as "Context_01"
participant undefined_02 as "undefined_02"
participant ERC20_02 as "ERC20_02"
participant SafeMath_02 as "SafeMath_02"

"EOA" -> "LendingPoolAddressesProviderMock_01" ++: deposit(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | _reserve | 0xDf8aaad058abEa00205d01Ad733Bd7A763E83883 |\n\
| uint | _amount | 1000000000000000000000 |\n\
| address | onBehalfOf | 0xC62DE65c47EC3D526B809af7610c6014529eEf2e |\n\
| uint | _referralCode | 0 |\n\
) { 0.0 GWEI }
"LendingPoolAddressesProviderMock_01" -> "MockERC20Mintable_01" ++: transferFrom(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | sender | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |\n\
| address | recipient | 0xC62DE65c47EC3D526B809af7610c6014529eEf2e |\n\
| uint | amount | 1000000000000000000000 |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "undefined_01" ++: unknown-internal-name()
"undefined_01" -> "ERC20_01" ++: _beforeTokenTransfer(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | from | 0xC62DE65c47EC3D526B809af7610c6014529eEf2e |\n\
| address | to | 0x00000000000000000000003635c9aDC5dEA00000 |\n\
| uint | amount | 1901 |\n\
) { 0.0 GWEI }
"ERC20_01" -> "SafeMath_01" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 1000000000000000000000 |\n\
| uint | b | 1000000000000000000000 |\n\
| string | errorMessage | 'ERC20: transfer amount exceeds balance' |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "ERC20_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"ERC20_01" -> "SafeMath_01" ++: add(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 70000000000000000000 |\n\
| uint | b | 1000000000000000000000 |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "ERC20_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 1070000000000000000000 |\n\
)
"ERC20_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "ERC20_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0xC62DE65c47EC3D526B809af7610c6014529eEf2e |\n\
)
"ERC20_01" -> "Context_01" ++: _msgSender()
"Context_01" -> "ERC20_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address |  | 0xC62DE65c47EC3D526B809af7610c6014529eEf2e |\n\
)
"ERC20_01" -> "SafeMath_01" ++: sub(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 1000000000000000000000 |\n\
| uint | b | 1000000000000000000000 |\n\
| string | errorMessage | 'ERC20: transfer amount exceeds allowance' |\n\
) { 0.0 GWEI }
"SafeMath_01" -> "ERC20_01" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 0 |\n\
)
"ERC20_01" -> "ERC20_01" ++: _approve(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | owner | 0x00000000000000000000003635c9aDC5dEA00000 |\n\
| address | spender | 0x0000000000000000000000000000000000000000 |\n\
| uint | amount | 1100 |\n\
) { 0.0 GWEI }
"ERC20_01" -> "ERC20_01" --: 
"LendingPoolAddressesProviderMock_01" -> "undefined_02" ++: unknown-internal-name()
"undefined_02" -> "ERC20_02" ++: _beforeTokenTransfer(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| address | from | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |\n\
| address | to | 0x00000000000000000000003635c9aDC5dEA00000 |\n\
| uint | amount | 4270 |\n\
) { 0.0 GWEI }
"ERC20_02" -> "SafeMath_02" ++: add(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 70000000000000000000 |\n\
| uint | b | 1000000000000000000000 |\n\
) { 0.0 GWEI }
"SafeMath_02" -> "ERC20_02" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 1070000000000000000000 |\n\
)
"ERC20_02" -> "SafeMath_02" ++: add(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint | a | 0 |\n\
| uint | b | 1000000000000000000000 |\n\
) { 0.0 GWEI }
"SafeMath_02" -> "ERC20_02" --: Return (\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| uint |  | 1000000000000000000000 |\n\
)
"ERC20_02" -> "undefined_02" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| LendingPoolAddressesProviderMock_01 | LendingPoolAddressesProviderMock | 0xC62DE65c47EC3D526B809af7610c6014529eEf2e |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0xDf8aaad058abEa00205d01Ad733Bd7A763E83883 |
<#FEFECE>| undefined_01 | undefined | 0xDf8aaad058abEa00205d01Ad733Bd7A763E83883 |
<#FEFECE>| ERC20_01 | ERC20 | 0xDf8aaad058abEa00205d01Ad733Bd7A763E83883 |
<#FEFECE>| SafeMath_01 | SafeMath | 0xDf8aaad058abEa00205d01Ad733Bd7A763E83883 |
<#FEFECE>| Context_01 | Context | 0xDf8aaad058abEa00205d01Ad733Bd7A763E83883 |
<#FEFECE>| undefined_02 | undefined | 0xC62DE65c47EC3D526B809af7610c6014529eEf2e |
<#FEFECE>| ERC20_02 | ERC20 | 0xC62DE65c47EC3D526B809af7610c6014529eEf2e |
<#FEFECE>| SafeMath_02 | SafeMath | 0xC62DE65c47EC3D526B809af7610c6014529eEf2e |
endlegend

@enduml