

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xdc593b177e0e1355bfd8db8f4795dffa1aff924ec48c019220b453003c854fa0


actor EOA as "EOA"
participant MockERC20Mintable_01 as "MockERC20Mintable_01"

"EOA" -> "MockERC20Mintable_01" ++: constructor(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| string | name | 'MINT' |\n\
| string | symbol | 'MINT' |\n\
) { 0.0 GWEI }
"MockERC20Mintable_01" -> "EOA" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| MockERC20Mintable_01 | MockERC20Mintable | 0xBAB15d629B84E2C9575Da294AB24b227e15fA02F |
endlegend

@enduml