

@startuml

autonumber
skinparam legendBackgroundColor #FEFECE

<style>
      header {
        HorizontalAlignment left
        FontColor purple
        FontSize 14
        Padding 10
      }
    </style>

header Insights by Truffle

title Txn Hash: 0xed642c001eae1c8283428e88678515b22400d7aaeb00faf0fa04e8b80bbb0ef7


actor EOA as "EOA"
participant LendingPoolAddressesProviderMock_01 as "LendingPoolAddressesProviderMock_01"

"EOA" -> "LendingPoolAddressesProviderMock_01" ++: constructor(\n\
<#FEFECE,#FEFECE>|= type |= name |= value |\n\
| string | name | 'TOKEN_NAME' |\n\
| string | symbol | 'TOKEN_SYMBOL' |\n\
) { 0.0 GWEI }
"LendingPoolAddressesProviderMock_01" -> "EOA" --: 

legend
Participant details
<#FEFECE,#D0D000>|= Alias |= Contract name |= Address |
<#FEFECE>| EOA | Externally Owned Account | 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 |
<#FEFECE>| LendingPoolAddressesProviderMock_01 | LendingPoolAddressesProviderMock | 0x2d4F8EeeBa4B944f395e6a9669410cF92f84913c |
endlegend

@enduml